# Generated by Django 5.1.7 on 2025-03-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySQL_CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerform',
            name='study_phase',
            field=models.CharField(choices=[('Phase I', 'Phase I'), ('Phase II', 'Phase II'), ('Phase III', 'Phase III'), ('Phase IV', 'Phase IV')], max_length=50),
        ),
    ]
