# Generated by Django 5.1.7 on 2025-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Studyname', models.CharField(max_length=100)),
                ('study_description', models.CharField(max_length=100)),
                ('study_phase', models.CharField(max_length=50)),
                ('sponsor_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'datas',
            },
        ),
    ]
